### ISSUE TITLE
The hints are still hidden when I start showing the answers

### ISSUE THREAD

**Issue by Kings89** [thiswillbeyourgithub/Oliver_Cloze#2]
If you can make it so that when I open the show answers the hints do not become boxes, It would be really helpful

Thank you

**Comment by thiswillbeyourgithub** [comment]
Hi

Can you clarify what you mean by "hint" and "box" please? 

A screenshot could be useful too.

**Comment by Kings89** [comment]
Here are the hints I am talking about 
![Screenshot 2020-11-18 000524](https://user-images.githubusercontent.com/44119890/99450612-05f55580-2932-11eb-80f6-d51affcafddc.jpg)

Here is the card with the hints on preview before showing the first cloze 
![Screenshot 2020-11-18 000607](https://user-images.githubusercontent.com/44119890/99450664-19a0bc00-2932-11eb-98d7-f78ead4c1f79.jpg)

See how the hints disappear as soon as I reveal the first cloze
![image](https://user-images.githubusercontent.com/44119890/99450706-29b89b80-2932-11eb-991c-ae16bebbeb2b.png)

It would be useful if the hints stayed as I am opening the clozes one by one, an example I could use this feature is like this 
![image](https://user-images.githubusercontent.com/44119890/99450856-68e6ec80-2932-11eb-8ac0-80327fa0a734.png)
![image](https://user-images.githubusercontent.com/44119890/99450901-769c7200-2932-11eb-93f2-ebef75f71ae6.png)

Thank you for replying and for trying to look into my suggestion

**Comment by thiswillbeyourgithub** [comment]
> Thank you for replying and for trying to look into my suggestion

Thank you for contributing :) 

Side note : I don't know for how long you have been using clozolkor but I need to point out that now, the hiding boxes are all of the same size, to avoid using the size as a hint. For exemple on your last picture the boxes are different size and this is usually an unwanted hint that helps you answering the card but won't help you actually remember it. Cheating if you will. I intend to publish a new version shortly so don't hesitate to subscribe to the repo.

Now for your request : 

What you're asking is not really that feasible. Let me explain. Cloze hints are information in the front of the card, and the boxe are appearing when you flipped the card, so looking at the back.

Implementing what you're asking means getting information from the front and using it when executing the js from the back, and I think this is not possible. This is the kind of things that "anki persistence" is tackling I think. So maybe it's doable, but I learned js by trying to put clozolkor together so I really have no deep understanding of all the gears behind it. Specifically : I won't be able to help when compatibility issues will appear as js is not handled the same way on ios, android and desktop.

So, if you run into someone who understands js way better than me, ask him to make a PR. Otherwise I can't do it without risking to break many things, sorry :/

**Comment by Kings89** [comment]
Yea I completely understand your point, and I just came across your custom deck and since I really love the cloze one by one card type I wanted to suggest this to you. 
I have sent anking as well about this, and I might look more into it and ask some more people  before I give up about it.

Thank you and have a nice day.

**Comment by thiswillbeyourgithub** [comment]
Hey, just figured you might be interested in the new release, check it out!
