### ISSUE TITLE
My model.

### ISSUE THREAD

**Issue by huandney** [thiswillbeyourgithub/Oliver_Cloze#6]
I thought about doing the same thing you told me, but I think it's better to post the model here, if you have any questions let me know.
It was more of a layout change and I added a question and answer system via `<details>`.
Tip: shortcut "w" to open the questions.

https://drive.google.com/file/d/1XGKFAOu5oMjW5WagGjJzUdSSKekm5OTb/view?usp=sharing

**Comment by thiswillbeyourgithub** [comment]
interesting.

I find it curious that you resorted to adding those extra questions instead of just adding a list of cloze like so :

```
something questionmark?
{{c1::answer1, but why? }}{{c1:: because X!, even though what?}}{{c1:: X is usually associated with reverse chronobaryobullshitism}}
```

I find it more "elegent" because there is no fixed limit (only 4 question), you can reveal letter by letter etc, you only use the first field so it's sometimes easier to query (Body:"*word*"   <- to find the word without searching through all the OCR text picture in the sources that contain the same word for example) and probably other reasons..

So I prefer using one very extensible template (mine) and have tons of different phrasing that having several tempaltes.

But to each his own.

**Comment by huandney** [comment]
> I find it curious that you resorted to adding those extra questions instead of just adding a list of cloze like so :

I have this scheme on almost all my cards, I got used to it. haha
